### ISSUE TITLE
可以请教一下数据库怎么创建吗？小白一枚

### ISSUE THREAD

**Issue by jcx70100** [fancoo/Proxy#1]
希望作者有时间能写个数据库创建教程，之前没接触过这些，有点茫然，但确实对您的成果感兴趣

**Comment by fancoo** [comment]
网络上关于建立table的教程很多，可以参考这一篇：[w3school-how to create table](https://www.w3schools.com/sql/sql_create_table.asp)

**Comment by mazzzystar** [comment]
网络上关于建立table的教程很多，可以参考这一篇：[w3school-how to create table](https://www.w3schools.com/sql/sql_create_table.asp)

**Comment by jcx70100** [comment]
@fancoo  非常感谢您的解答，我在参考了网页后，创建了数据库，但是执行ip_pool.py似乎并不顺利，问题可能还是在数据库上，是将文件写成固定格式保存，然后再执行py文件吗？保存的文件名有什么要求，或者执行的时候要加什么参数嘛？ 对这块不是很了解，还希望您能指点迷津。 那段数据库代码是加在哪的？
```
CREATE TABLE IP(
	content varchar(30),
	test_times int,
	failure_times int,
	success_rate float,
	avg_response_time float,
	score float,
);
```

**Comment by mazzzystar** [comment]
@jcx70100 数据库只要创建就行了，不需要嵌入代码内。修改代码中这一段：
```python
# database config
config = {
    'host': '127.0.0.1',
    'port': 3306,
    'user': 'root',
    'passwd': '*****',
    'db': 'proxy',
    'charset': 'utf8'
}
TABLE_NAME = 'valid_ip'
```
改成你自己的用户名密码和表名就行。

**Comment by jcx70100** [comment]
@fancoo  您好，感谢您的指点。
我在ubuntu下安装了mysql并创建了数据库proxy，在数据库中按要求创建了table，名字为IP；
在修改了#database config 字段，修改成mysql的用户名和密码，以及table名称，在终端实行ip_pool.py后就卡住不动了，也没有进度提示，不知道哪里出了问题。

自己修改的用户名和密码是mysql的还是系统的用户名和密码呢？
需不需要把文件复制到数据库所在目录在执行呢？

**Comment by mazzzystar** [comment]
@jcx70100 有报错信息能贴出来吗？你的两个问题：1.是自己的用户密码。2.不需要。

**Comment by jcx70100** [comment]
@fancoo  好的，具体配置如下：
## mysql数据库我是这么设置的
数据库proxy：
![2017-06-13 3 17 01](https://user-images.githubusercontent.com/18900117/27070533-0359eed4-504c-11e7-97ce-309e0099ba5c.png)

table：
![2017-06-13 3 17 31](https://user-images.githubusercontent.com/18900117/27070547-156f8dc2-504c-11e7-8ac4-45ee69d15d23.png)

![2017-06-13 3 18 05](https://user-images.githubusercontent.com/18900117/27070553-1af254f0-504c-11e7-9e17-fa14e4074a55.png)

## 文件参数修改

![2017-06-13 3 18 54](https://user-images.githubusercontent.com/18900117/27070566-2a9124a4-504c-11e7-92a5-727ba94243da.png)

## 执行结果

![2017-06-13 3 19 38](https://user-images.githubusercontent.com/18900117/27070577-33ce07a8-504c-11e7-96eb-6b9c2f627d18.png)

就卡在这里不动了，使用了系统用户名和密码也是一样。

**Comment by mazzzystar** [comment]
@jcx70100 我刚修改了代码的一处，你再pull下来试试~  代码过于久远待我哪天有空再维护一下吧。

**Comment by jcx70100** [comment]
@fancoo  十分感谢

**Comment by mazzzystar** [comment]
@jcx70100 看看我的[BaiduCrawler](https://github.com/fancoo/BaiduCrawler)项目吧，在那里我重构了代码。
