### ISSUE TITLE
觉得爬到的HTTP代理很奇怪

### ISSUE THREAD

**Issue by kxltsuper** [fancoo/Proxy#2]
你好，我使用此程序爬到了不少代理，但是使用这些代理，只能访问百度，却无法访问别的网站，(即如果不是用百度作为筛选网站，几乎得不到可用代理)，请问这是怎么回事？

**Comment by mazzzystar** [comment]
@kxltsuper 我试了一下爬取豆瓣主页，没有问题。你确定已经存入数据库了吗。

**Comment by kxltsuper** [comment]
@fancoo 是的，我就是从MySQL中选出了几条来进行测试的。然后为了确保我的测试，我把程序ip_pool.py中的关于验证函数get_valid_ip中的url = 'https://www.baidu.com'改成url='http://www.sohu.com/'，结果就筛选不到有效代理了，程序显示都没有开始第一轮的round，看一下数据库为空...

**Comment by kxltsuper** [comment]
@fancoo 我又测试了一下豆瓣，https://www.douban.com，发现确实可以。难道是这些代理能够对https有效，但对http无效吗？

**Comment by mazzzystar** [comment]
@kxltsuper 存在这样的可能性，毕竟用于测试的baidu也是https，我后续看一下吧。

**Comment by WilliamYang1992** [comment]
@fancoo 我认为你应该判断r.status_code而不是r.text会更好, 因为即使代理不可用, 也可能会返回类似认证失败的页面, 用你的IP测试腾讯qq.com,大部分都访问不了,可以考虑下更改逻辑 ,同时,建议OSError改为requests.RequestException会更好

**Comment by mazzzystar** [comment]
@WilliamYang1992 我确实忘记这一点了，感谢提醒~
